language: objective-c
osx_image: xcode9
install: gem install xcpretty
script:
  - xcodebuild clean build test -project "YLTableView.xcodeproj" -scheme "YLTableView" -destination "platform=iOS Simulator,name=iPhone 8" | xcpretty
